"""GitHubClient protocol — the port all GitHub access goes through (Tech Spec §9.1).

Role protocol (used by the orchestrator and role crews) plus admin protocol
(constructed only inside `codie init` / `codie doctor`).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from codie.models import (
    GitHubComment,
    GitHubIssue,
    GitHubPR,
    GitHubReview,
    RequiredCheck,
    TimelineEvent,
)


@runtime_checkable
class GitHubClient(Protocol):
    """The role protocol."""

    # The identity performing the current operation (per-role token routing).
    actor: str

    def set_actor(self, actor: str) -> None: ...

    def list_issues(self, since: str | None = None) -> list[GitHubIssue]: ...
    def get_issue(self, number: int) -> GitHubIssue | None: ...
    def create_issue(self, title: str, body: str, labels: list[str]) -> GitHubIssue: ...
    def edit_issue(self, number: int, body: str | None = None, title: str | None = None) -> GitHubIssue | None: ...
    def set_labels(self, number: int, labels: list[str]) -> None: ...
    def set_assignees(self, number: int, logins: list[str]) -> None: ...
    def comment(self, number: int, body: str) -> GitHubComment: ...
    def list_comments(self, since: str | None = None) -> list[GitHubComment]: ...
    def list_timeline(self, number: int) -> list[TimelineEvent]: ...
    def list_prs(self) -> list[GitHubPR]: ...
    def get_pr(self, number: int) -> GitHubPR | None: ...
    def pr_reviews(self, number: int) -> list[GitHubReview]: ...
    def list_pr_files(self, number: int) -> list[str]: ...
    def list_review_comments(self, number: int) -> list[dict]: ...
    def create_pr(self, title: str, body: str, head: str, base: str, draft: bool = False) -> GitHubPR: ...
    def update_pr(
        self,
        number: int,
        title: str | None = None,
        body: str | None = None,
        draft: bool | None = None,
    ) -> GitHubPR | None: ...
    def close_pr(self, number: int) -> None: ...
    def create_review(
        self, pr_number: int, state: str, body: str, comments: list[dict] | None = None
    ) -> GitHubReview: ...
    def merge_pr(self, number: int, merge_method: str = "squash") -> bool: ...
    def reopen_issue(self, number: int) -> None: ...
    def close_issue(self, number: int) -> None: ...
    def get_file(self, path: str, ref: str) -> str | None: ...
    def get_ref(self, branch: str) -> str | None: ...
    def list_required_checks(self, ref: str) -> list[RequiredCheck]: ...
    def set_commit_status(self, ref: str, state: str, description: str = "") -> None: ...
    def upsert_label(self, name: str, color: str, description: str = "") -> None: ...


@runtime_checkable
class AdminGitHubClient(GitHubClient, Protocol):
    """The admin protocol — constructed only inside `codie init` / `codie doctor`.

    It extends the read/issue surface so provisioning can adopt issues and post
    comments under the admin identity.
    """

    def pin_issue(self, number: int, pinned: bool) -> None: ...
    def create_ref(self, branch: str, sha: str) -> None: ...
    def upsert_file(self, path: str, content: str, message: str, branch: str) -> str: ...
    def get_branch_protection(self, branch: str) -> dict | None: ...
    def update_branch_protection(
        self,
        branch: str,
        require_prs: bool,
        require_approvals: int,
        checks: list[str] | None = None,
    ) -> None: ...
    def update_repo(self, merge_method: str, delete_branch_on_merge: bool = True) -> None: ...
    def invite_collaborator(self, login: str, permission: str = "push") -> None: ...
    def get_authenticated_user(self) -> str: ...
